config/routes.rb
Rails.application.routes.draw do
  resources :restaurants

  root 'restaurants#index'

end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
  has_many :reviews

  validates :name, null: false
  validates :address, null: false
  validates :city, null: false
  validates :state, null: false
  validates :zip_code, null: false
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :restaurant

  validates :rating, null: false, inclusion: { within: 1..5 }
  validates :body, null: false
  # validates :date, null: false
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  def index
    @restaurants = Restaurant.all
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)

    if @restaurant.save
      redirect_to @restaurant
    else
      render 'new'
    end
  end

  def show
    @restaurant = Restaurant.find(params[:id])
    @review = Review.new
  end

  private
### Something is happening here.  The '/restuaraunts' page works when directly going there,
### but if redirected, it crashes.
    def restaurant_params
      params.require(:restaurant).permit(:name, :address, :city, :state, :zipcode,
        :description, :category)
    end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def index
  end

  def new
  end

  def show
  end

  def create
    @restaurant = Restaurant.find(params[:id])
    @review = Review.new(review_params)
    @review.save

    redirect_to @restaurant
  end

  private

    def review_params
      results = params.require(:review).permit(:id, :rating, :body)
      results[:id] = params[:id]
      results
    end

    # def review_params
    #   params.require(:review).permit(:rating, :body)
    # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GoodEats</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/restaurants/index.html.erb
<h1>Restaurant Listings</h1>

<ul>
  <% @restaurants.each do |restaurant| %>
    <li>
      <%= link_to "#{restaurant.name}", restaurant_path(restaurant) %><br/>
    </li>
  <% end %>
</ul>

<div>
  <%= link_to "New Restaurant", new_restaurant_path %>
</div><br/>

app/views/restaurants/new.html.erb
<h1>New Restaurant</h1>

<%= form_for @restaurant do |f| %>

  <% if @restaurant.errors.any? %>
    <ul>
      <% @restaurant.errors.full_messages.each do |msg| %>
        <li> <%= msg %></li>
      <% end %>
    </ul>
  <% end %>

  <div>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div>
    <%= f.label :address %>
    <%= f.text_field :address %>
  </div>

  <div>
    <%= f.label :city %>
    <%= f.text_field :city %>
  </div>

  <div>
    <%= f.label :state %>
    <%= f.text_field :state %>
  </div>

  <div>
    <%= f.label :zipcode %>
    <%= f.text_field :zipcode %>
  </div>

  <div>
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div>
    <%= f.label :category %>
    <%= f.text_field :category %>
  </div>
  <br/>

  <%= f.submit 'Submit' %>
<% end %>

app/views/restaurants/show.html.erb
<h1>Restaurants</h1>

<h3><%= @restaurant.name %></h3>

<strong><%= "#{@restaurant.address}" %></strong><br>
<strong><%= "#{@restaurant.city}, #{@restaurant.state}, #{@restaurant.zipcode}" %></strong><br><br>

<div><%= @restaurant.description %></div><br/>
<div><%= link_to "Return to restaurant list", restaurants_path %></div></br>

<h3>Review this restaurant</h3>
<%= form_for :review, url: restaurants_path do |f| %>
  <p>
    <%= f.label :rating %><br>
    <%= f.text_field :rating %>
  </p>

  <p>
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>